import { useEffect, useState } from "react";
import { BookOpen, RefreshCw, ShieldAlert } from "lucide-react";
import { customFetch } from "@workspace/api-client-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";

export function DemoSettings() {
  const { toast } = useToast(); const [preview, setPreview] = useState<Record<string, number>>({}); const [confirmation, setConfirmation] = useState("");
  useEffect(() => { customFetch<any>("/api/demo/reset/preview", { responseType: "json" }).then((data) => setPreview(data.demoRecords || {})).catch(() => undefined); }, []);
  const reset = async (scope: string) => { const result = await customFetch<any>("/api/demo/reset", { method: "POST", responseType: "json", body: JSON.stringify({ scope, confirmation }) }); toast({ title: "Demo restored", description: result.message }); };
  return <Card className="border-primary/20"><CardHeader><div className="flex items-center gap-3"><div className="rounded-xl bg-primary/10 p-2.5 text-primary"><BookOpen className="h-5 w-5" /></div><div><CardTitle>Demo Environment</CardTitle><CardDescription>Baseline 2026.1 · team-created records are protected during normal resets.</CardDescription></div></div></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{Object.entries(preview).map(([key,value]) => <div key={key} className="rounded-lg bg-muted p-3"><p className="text-lg font-bold">{value}</p><p className="text-xs capitalize text-muted-foreground">{key}s</p></div>)}</div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => window.dispatchEvent(new Event("knox:demo-center"))}><BookOpen className="mr-2 h-4 w-4" />Open Demo Center</Button><AlertDialog><AlertDialogTrigger asChild><Button variant="outline"><RefreshCw className="mr-2 h-4 w-4" />Reset demo progress</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Restore demo progress?</AlertDialogTitle><AlertDialogDescription>This restarts every guided mission. Curated baseline and team-created business records are preserved.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => void reset("all")}>Restore</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><AlertDialog><AlertDialogTrigger asChild><Button variant="destructive"><ShieldAlert className="mr-2 h-4 w-4" />Factory reset</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Factory reset is destructive</AlertDialogTitle><AlertDialogDescription>This is reserved for an authenticated owner and can remove team-entered records. Type DELETE ALL DATA to enable it.</AlertDialogDescription></AlertDialogHeader><Input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder="DELETE ALL DATA" /><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={confirmation !== "DELETE ALL DATA"} onClick={() => void reset("factory")}>Factory reset</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></CardContent></Card>;
}
