import { useEffect, useState } from "react";
import { customFetch } from "@workspace/api-client-react";
import { AlertCircle, CheckCircle2, ExternalLink, Loader2, RefreshCw, Unplug } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";

type Status = { configured: boolean; connection: { connected: boolean; status: string; companyName?: string; realmId?: string; environment?: string; readinessStatus: string; lastSyncAt?: string } };
type QueueItem = { id: string; entityType: string; localId: string; action: string; status: string; warnings: string[]; lastError?: string; createdAt: string };
type Candidate = { entityType: string; localId: string; localName: string; matches: { id: string; name: string; confidence: string }[] };

export function QuickBooksSettings() {
  const { toast } = useToast(); const [status, setStatus] = useState<Status>(); const [queue, setQueue] = useState<QueueItem[]>([]); const [selected, setSelected] = useState<string[]>([]); const [candidates, setCandidates] = useState<Candidate[]>([]); const [busy, setBusy] = useState("");
  const load = async () => { const [s, q] = await Promise.all([customFetch<Status>("/api/quickbooks/status", { responseType: "json" }), customFetch<QueueItem[]>("/api/quickbooks/queue", { responseType: "json" })]); setStatus(s); setQueue(q); };
  useEffect(() => { load().catch(() => undefined); }, []);
  const run = async (name: string, task: () => Promise<unknown>, success: string) => { setBusy(name); try { await task(); toast({ title: success }); await load(); } catch (error) { toast({ title: "QuickBooks action failed", description: error instanceof Error ? error.message : String(error), variant: "destructive" }); } finally { setBusy(""); } };
  const connect = async () => { const result = await customFetch<{ authorizationUrl: string }>("/api/quickbooks/connect", { responseType: "json" }); window.location.assign(result.authorizationUrl); };
  const reconcile = async () => { const result = await customFetch<{ candidates: Candidate[] }>("/api/quickbooks/reconcile", { method: "POST", responseType: "json" }); setCandidates(result.candidates); return result; };
  const decide = async (candidate: Candidate, decision: "link" | "ignore", quickbooksId = "") => { await run(`map-${candidate.localId}`, () => customFetch(`/api/quickbooks/entity-mappings/${candidate.entityType}/${candidate.localId}`, { method: "PUT", body: JSON.stringify({ decision, quickbooksId }), responseType: "json" }), `${candidate.localName} reconciled`); setCandidates(v => v.filter(x => x.localId !== candidate.localId || x.entityType !== candidate.entityType)); };
  const pending = queue.filter((q) => q.status === "pending_approval"); const failures = queue.filter((q) => q.status === "failed");
  return <div className="space-y-4">
    <Card>
      <CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2">QuickBooks Online {status?.connection.connected ? <CheckCircle2 className="h-5 w-5 text-emerald-600" /> : <AlertCircle className="h-5 w-5 text-amber-600" />}</CardTitle><CardDescription>Approval-based accounting synchronization. Knox remains your operations system.</CardDescription></div><Badge variant={status?.connection.connected ? "default" : "secondary"}>{status?.connection.status?.replaceAll("_", " ") ?? "Loading"}</Badge></div></CardHeader>
      <CardContent className="space-y-4">
        {!status?.configured && <div className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-3 text-sm">Add the Intuit client ID, client secret, redirect URL, webhook verifier, and encryption key to DigitalOcean before connecting.</div>}
        {status?.connection.connected && <div className="grid gap-2 text-sm sm:grid-cols-2"><div><span className="text-muted-foreground">Company:</span> {status.connection.companyName || status.connection.realmId}</div><div><span className="text-muted-foreground">Environment:</span> {status.connection.environment}</div><div><span className="text-muted-foreground">Readiness:</span> {status.connection.readinessStatus.replaceAll("_", " ")}</div><div><span className="text-muted-foreground">Last import:</span> {status.connection.lastSyncAt ? new Date(status.connection.lastSyncAt).toLocaleString() : "Not yet"}</div></div>}
        <div className="flex flex-wrap gap-2"><Button onClick={() => run("connect", connect, "Opening QuickBooks")} disabled={!status?.configured || busy !== ""}>{busy === "connect" ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ExternalLink className="mr-2 h-4 w-4" />}{status?.connection.connected ? "Reconnect" : "Connect QuickBooks"}</Button>{status?.connection.connected && <><Button variant="outline" disabled={busy !== ""} onClick={() => run("reconcile", reconcile, "QuickBooks lists imported for reconciliation")}>{busy === "reconcile" ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <RefreshCw className="mr-2 h-4 w-4" />}Import & reconcile</Button><Button variant="outline" disabled={busy !== ""} onClick={() => run("disconnect", () => customFetch("/api/quickbooks/disconnect", { method: "POST" }), "QuickBooks disconnected")}><Unplug className="mr-2 h-4 w-4" />Disconnect</Button></>}</div>
      </CardContent>
    </Card>
    {candidates.length > 0 && <Card><CardHeader><CardTitle>Reconcile existing records</CardTitle><CardDescription>Suggested links require your approval. Ambiguous records are never merged automatically.</CardDescription></CardHeader><CardContent className="space-y-2">{candidates.map(c => <div key={`${c.entityType}-${c.localId}`} className="rounded-lg border p-3"><div className="font-medium">{c.localName} <span className="text-xs font-normal text-muted-foreground">({c.entityType})</span></div><div className="mt-2 flex flex-wrap gap-2">{c.matches.map(m => <Button key={m.id} size="sm" variant="outline" disabled={busy !== ""} onClick={() => void decide(c, "link", m.id)}>Link to {m.name} · {m.confidence}</Button>)}<Button size="sm" variant="ghost" disabled={busy !== ""} onClick={() => void decide(c, "ignore")}>Ignore</Button>{c.matches.length === 0 && <span className="text-xs text-muted-foreground self-center">No confident match—create it through the approval queue.</span>}</div></div>)}</CardContent></Card>}
    <Card><CardHeader><CardTitle>Accounting approval queue</CardTitle><CardDescription>Nothing is exported until an owner approves it.</CardDescription></CardHeader><CardContent className="space-y-3">
      {pending.length === 0 ? <p className="text-sm text-muted-foreground">No records are awaiting approval.</p> : pending.map(item => <label key={item.id} className="flex items-start gap-3 rounded-lg border p-3"><input className="mt-1" type="checkbox" checked={selected.includes(item.id)} onChange={(e) => setSelected(v => e.target.checked ? [...v, item.id] : v.filter(id => id !== item.id))} /><div className="min-w-0 flex-1"><div className="font-medium capitalize">{item.entityType} · {item.action}</div><div className="text-xs text-muted-foreground">Local record {item.localId}</div>{item.warnings?.map(w => <div key={w} className="mt-1 text-xs text-amber-600">{w}</div>)}</div></label>)}
      {pending.length > 0 && <Button disabled={!selected.length || busy !== ""} onClick={() => run("approve", () => customFetch("/api/quickbooks/queue/approve", { method: "POST", body: JSON.stringify({ ids: selected }), responseType: "json" }), `${selected.length} record(s) approved`).then(() => setSelected([]))}>Approve selected</Button>}
    </CardContent></Card>
    {failures.length > 0 && <Card><CardHeader><CardTitle>Exceptions</CardTitle><CardDescription>Validation errors stay paused until corrected. Retry transient failures here.</CardDescription></CardHeader><CardContent className="space-y-2">{failures.map(item => <div key={item.id} className="flex items-center justify-between gap-3 rounded-lg border border-destructive/30 p-3"><div><div className="font-medium capitalize">{item.entityType}</div><div className="text-xs text-destructive">{item.lastError}</div></div><Button size="sm" variant="outline" onClick={() => run(`retry-${item.id}`, () => customFetch(`/api/quickbooks/queue/${item.id}/retry`, { method: "POST", responseType: "json" }), "Retry scheduled")}>Retry</Button></div>)}</CardContent></Card>}
  </div>;
}
