import type {
  JobInsert,
  LeadInsert,
  MaterialInsert,
  ProductInsert,
  ProposalInsert,
  SalespersonInsert,
  InvoiceInsert,
  SettingsInsert,
  CommunicationInsert,
  MeasurementInsert,
  TaskInsert,
} from "@workspace/db";

const now = new Date().toISOString();

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

const FICTIONAL_LEAD_NAMES = ["Maya Brooks","Ethan Caldwell","Nora Fleming","Caleb Monroe","Ava Patterson","Miles Bennett","Elena Harper","Owen Carlisle","Lucy Hart","Theo Griffin","Ivy Dawson","Noah Mercer","Grace Holloway","Liam Spencer","Chloe Barrett","Henry Walsh","Ella Rhodes","Jack Whitaker","Mia Sutton","Leo Chandler","Sofia Grant","Wyatt Palmer","Lily Foster","Isaac Webb","Zoe Marshall","Finn Lawson","Ruby Kendall","Cole Ramsey","Anna Pierce"];
const GENERATED_LEADS: LeadInsert[] = FICTIONAL_LEAD_NAMES.map((customerName, index) => ({
  id: `demo-lead-${index + 8}`, customerName, phone: `865-555-${String(1200 + index)}`, email: `${customerName.toLowerCase().replace(/\s+/g, ".")}@example.com`, address: `${110 + index} Demo Ridge Lane`, city: ["Knoxville","Farragut","Maryville","Oak Ridge","Powell"][index % 5], flooringInterest: ["Luxury Vinyl Plank (LVP)","Carpet","Hardwood","Tile","Laminate"][index % 5], estimatedValue: 4800 + (index % 7) * 1750, source: ["Website","Referral","Walk-in","Repeat Customer","Google"][index % 5], stage: ["New Lead","Contacted","Measurement Scheduled","Estimate Completed","Proposal Sent","Won","Lost"][index % 7], salesperson: index % 2 ? "Jenn Hedley" : "Will Hedley", followUpDate: daysFromNow((index % 14) - 4), estimatedSqft: 450 + (index % 8) * 175, interestLevel: index % 3 === 0 ? "High" : "Medium", notes: "Fictional demonstration lead for the rolling 90-day business view.", createdAt: new Date(Date.now() - (index + 3) * 2 * 86400000).toISOString(), updatedAt: now,
}));

const GENERATED_PRODUCTS: ProductInsert[] = [
  ["PetShield Premium Pad","Padding","PAD-PET-08","sqft",0.68,1.35], ["QuietStep LVP Underlayment","Underlayment","UND-QS-100","sqft",0.54,1.15], ["Oak Stair Nose","Trim","TRM-OAK-SN","piece",24,49], ["Waterproof Quarter Round","Trim","TRM-WP-QR","piece",9,19], ["Commercial Pressure Adhesive","Installation","ADH-COM-4G","each",82,145], ["Floor Preparation Service","Installation","SVC-PREP","sqft",0.85,1.95],
].map(([name,category,sku,unit,cost,price], index) => ({ id:`demo-product-${19+index}`, name:String(name), category:String(category), sku:String(sku), supplier:index < 2 ? "Demo Flooring Supply" : "East Tennessee Materials", unit:String(unit), cost:Number(cost), price:Number(price), quantityOnHand:index === 5 ? 0 : 120 + index * 25, inventoryType:index === 5 ? "Service" : "Inventory", active:true, notes:"Fictional demo catalog item.", createdAt:now, updatedAt:now }));

const GENERATED_PROPOSALS: ProposalInsert[] = Array.from({ length: 12 }, (_, index) => ({ id:`demo-proposal-${index+3}`, jobId:String(index+9), customerName:FICTIONAL_LEAD_NAMES[index], projectLocation:`${118+index} Demo Ridge Lane, Knoxville, TN`, flooringType:["Luxury Vinyl Plank (LVP)","Carpet","Hardwood","Tile"][index%4], roomList:[{id:`dp-room-${index}`,name:"Main Living Area",length:24+index,width:18}], lineItems:[], salespersonId:index%2?"1":"2", totalSqFt:(24+index)*18, scopeOfWork:"Remove existing flooring, prepare substrate, install selected flooring and transitions, and complete final cleanup.", estimatedPrice:6200+index*975, expectedTimeline:`${2+(index%3)} working days`, materialAssumptions:"Final quantities subject to field verification.", exclusions:"Structural repair and concealed moisture damage.", warrantyNote:"Manufacturer and installation warranties apply.", depositType:"percent" as const, depositValue:50, paymentTerms:"50% deposit; balance at substantial completion.", status:["Draft","Sent","Viewed","Accepted","Declined","Expired"][index%6], shareToken:`demo-proposal-token-${index+3}`, sentAt:index%6===0?null:daysFromNow(-index-5), createdAt:new Date(Date.now()-(index+8)*4*86400000).toISOString() }));

const GENERATED_INVOICES: InvoiceInsert[] = Array.from({ length: 6 }, (_, index) => { const total=7200+index*1850, paid=index===0?0:index===1?total/2:index===2?total:index===3?total-750:index===4?total:total-1200; return { id:`demo-invoice-${index+7}`, invoiceNumber:`INV-${1107+index}`, jobId:String(index+9), jobNumber:`J-${1009+index}`, customerName:FICTIONAL_LEAD_NAMES[index], lineItems:[{id:`di-${index}-1`,description:"Flooring materials and professional installation",category:"Materials" as const,quantity:1,unitPrice:total/1.0975}], subtotal:Number((total/1.0975).toFixed(2)), taxableAmount:Number((total/1.0975).toFixed(2)), taxAmount:Number((total-total/1.0975).toFixed(2)), total, depositAmount:index?1000:0, paidAmount:paid, balanceAmount:total-paid, refundedAmount:index===4?350:0, taxCode:"TN-KNOX", paymentReference:paid?`DEMO-PMT-${index+1}`:"", paidAt:paid===total?daysFromNow(-index-2):null, status:index===0?"Draft":index===1?"Partial":index===2?"Paid":index===3?"Overdue":index===4?"Refunded":"Sent", issueDate:daysFromNow(-index*8-8), dueDate:daysFromNow(14-index*8), notes:"Fictional invoice for executive demonstration.", createdAt:new Date(Date.now()-(index+3)*9*86400000).toISOString(), updatedAt:now }; });

export const SEED_JOBS: JobInsert[] = [
  {
    id: "1",
    jobNumber: "J-1001",
    customerName: "Sarah Thompson",
    phone: "865-555-0101",
    email: "sarah.t@example.com",
    address: "123 Oak Lane",
    city: "Farragut",
    flooringType: "Luxury Vinyl Plank (LVP)",
    rooms: [{ id: "r1", name: "Living Room", length: 25, width: 50 }],
    squareFootage: 1250,
    crewAssigned: "Crew A",
    estStartDate: "2023-11-15",
    estCompletionDate: "2023-11-17",
    materialStatus: "Received",
    laborEstimate: 3125,
    materialEstimate: 4500,
    estRevenue: 11850,
    estGrossProfit: 4225,
    grossMarginPct: 35.6,
    notes: "Customer requested quiet underlayment.",
    priorityLevel: "Medium",
    riskLevel: "Low",
    status: "Approved",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "2",
    jobNumber: "J-1002",
    customerName: "Mike Reynolds",
    phone: "865-555-0102",
    email: "mike.r@example.com",
    address: "456 Pine Rd",
    city: "Maryville",
    flooringType: "Carpet",
    rooms: [{ id: "r2", name: "Master Bedroom", length: 28, width: 35 }],
    squareFootage: 980,
    crewAssigned: "Crew B",
    estStartDate: "2023-11-10",
    estCompletionDate: "2023-11-11",
    materialStatus: "In Transit",
    laborEstimate: 1470,
    materialEstimate: 3000,
    estRevenue: 6900,
    estGrossProfit: 2430,
    grossMarginPct: 35.2,
    notes: "Needs pet-friendly carpet padding.",
    priorityLevel: "High",
    riskLevel: "Low",
    status: "Scheduled",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "3",
    jobNumber: "J-1003",
    customerName: "Amy Carter",
    phone: "865-555-0103",
    email: "amy.c@example.com",
    address: "789 Birch St",
    city: "Oak Ridge",
    flooringType: "Hardwood",
    rooms: [{ id: "r3", name: "Main Floor", length: 40, width: 40 }],
    squareFootage: 1600,
    crewAssigned: "Crew C",
    estStartDate: "2023-11-20",
    estCompletionDate: "2023-11-25",
    materialStatus: "Ordered",
    laborEstimate: 6400,
    materialEstimate: 7000,
    estRevenue: 18750,
    estGrossProfit: 5350,
    grossMarginPct: 28.5,
    notes: "Requires 72hr acclimation time.",
    priorityLevel: "Medium",
    riskLevel: "Medium",
    status: "Material Ordered",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "4",
    jobNumber: "J-1004",
    customerName: "Green Valley Dental",
    phone: "865-555-0104",
    email: "admin@greenvalleydental.com",
    address: "101 Medical Way",
    city: "Knoxville",
    flooringType: "Commercial LVT",
    rooms: [{ id: "r4", name: "Clinic", length: 70, width: 40 }],
    squareFootage: 2800,
    crewAssigned: "Crew A",
    estStartDate: "2023-11-01",
    estCompletionDate: "2023-11-05",
    materialStatus: "Received",
    laborEstimate: 8400,
    materialEstimate: 12000,
    estRevenue: 31500,
    estGrossProfit: 11100,
    grossMarginPct: 35.2,
    actualRevenue: 31500,
    actualLaborCost: 8900,
    actualMaterialCost: 12400,
    actualAddOnCost: 1700,
    notes: "After-hours installation required.",
    priorityLevel: "High",
    riskLevel: "High",
    status: "In Progress",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "5",
    jobNumber: "J-1005",
    customerName: "Jason Miller",
    phone: "865-555-0105",
    email: "jason.m@example.com",
    address: "202 Mountain View",
    city: "Sevierville",
    flooringType: "Tile",
    rooms: [{ id: "r5", name: "Kitchen & Bath", length: 24, width: 30 }],
    squareFootage: 720,
    crewAssigned: "Crew D",
    estStartDate: "2023-12-01",
    estCompletionDate: "2023-12-04",
    materialStatus: "Delayed",
    laborEstimate: 3600,
    materialEstimate: 2500,
    estRevenue: 9850,
    estGrossProfit: 3750,
    grossMarginPct: 38.0,
    notes: "Customer changing mind on grout color. Long drive time.",
    priorityLevel: "Medium",
    riskLevel: "High",
    status: "Estimate Completed",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "6",
    jobNumber: "J-1006",
    customerName: "Brenda Wallace",
    phone: "865-555-0106",
    email: "brenda.w@example.com",
    address: "303 River Rd",
    city: "Lenoir City",
    flooringType: "Waterproof Flooring",
    rooms: [{ id: "r6", name: "Basement", length: 33, width: 33.33 }],
    squareFootage: 1100,
    crewAssigned: "Unassigned",
    materialStatus: "Ordered",
    laborEstimate: 3300,
    materialEstimate: 3500,
    estRevenue: 10400,
    estGrossProfit: 3600,
    grossMarginPct: 34.6,
    notes: "Check moisture levels before install.",
    priorityLevel: "Medium",
    riskLevel: "Medium",
    status: "Proposal Sent",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "7",
    jobNumber: "J-1007",
    customerName: "David Morgan",
    phone: "865-555-0107",
    email: "david.m@example.com",
    address: "404 Valley Dr",
    city: "Alcoa",
    flooringType: "Laminate",
    rooms: [{ id: "r7", name: "Upstairs", length: 30, width: 30 }],
    squareFootage: 900,
    crewAssigned: "Crew A",
    materialStatus: "Received",
    laborEstimate: 2250,
    materialEstimate: 2000,
    estRevenue: 7250,
    estGrossProfit: 3000,
    grossMarginPct: 41.3,
    actualRevenue: 7250,
    actualLaborCost: 3050,
    actualMaterialCost: 3450,
    actualAddOnCost: 500,
    notes: "Completed ahead of schedule.",
    priorityLevel: "Low",
    riskLevel: "Low",
    status: "Completed",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "8",
    jobNumber: "J-1008",
    customerName: "Summit Church Office",
    phone: "865-555-0108",
    email: "facilities@summitchurch.example",
    address: "505 Church St",
    city: "Powell",
    flooringType: "Commercial Carpet Tile",
    rooms: [{ id: "r8", name: "Offices", length: 80, width: 40 }],
    squareFootage: 3200,
    crewAssigned: "Crew B",
    estStartDate: "2023-11-20",
    estCompletionDate: "2023-11-22",
    materialStatus: "Received",
    laborEstimate: 4800,
    materialEstimate: 14000,
    estRevenue: 29600,
    estGrossProfit: 10800,
    grossMarginPct: 36.4,
    notes: "Lift systems needed for cubicles.",
    priorityLevel: "Medium",
    riskLevel: "Low",
    status: "Material Received",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "9",
    jobNumber: "J-1009",
    customerName: "Karen Wilson",
    phone: "865-555-0109",
    email: "karen.w@example.com",
    address: "606 Lakeview",
    city: "Tellico Village",
    flooringType: "Hardwood",
    rooms: [{ id: "r9", name: "Whole House", length: 50, width: 42 }],
    squareFootage: 2100,
    crewAssigned: "Unassigned",
    materialStatus: "Ordered",
    laborEstimate: 8400,
    materialEstimate: 9000,
    estRevenue: 24800,
    estGrossProfit: 7400,
    grossMarginPct: 29.8,
    notes: "Needs estimate scheduled.",
    priorityLevel: "High",
    riskLevel: "Low",
    status: "New Lead",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "10",
    jobNumber: "J-1010",
    customerName: "Rob Jenkins",
    phone: "865-555-0110",
    email: "rob.j@example.com",
    address: "707 Tech Parkway",
    city: "Hardin Valley",
    flooringType: "Luxury Vinyl Plank (LVP)",
    rooms: [{ id: "r10", name: "First Floor", length: 50, width: 29 }],
    squareFootage: 1450,
    crewAssigned: "Crew A",
    estStartDate: "2023-11-28",
    estCompletionDate: "2023-11-30",
    materialStatus: "In Transit",
    laborEstimate: 3625,
    materialEstimate: 5000,
    estRevenue: 13700,
    estGrossProfit: 5075,
    grossMarginPct: 37.0,
    notes: "",
    priorityLevel: "Medium",
    riskLevel: "Low",
    status: "Scheduled",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "11",
    jobNumber: "J-1011",
    customerName: "Patricia Evans",
    phone: "865-555-0111",
    email: "pat.e@example.com",
    address: "808 Cedar Ave",
    city: "Clinton",
    flooringType: "Carpet",
    rooms: [{ id: "r11", name: "Bedrooms", length: 40, width: 30 }],
    squareFootage: 1200,
    crewAssigned: "Unassigned",
    materialStatus: "Ordered",
    laborEstimate: 1800,
    materialEstimate: 3200,
    estRevenue: 7500,
    estGrossProfit: 2500,
    grossMarginPct: 33.3,
    notes: "Customer wants premium padding.",
    priorityLevel: "Low",
    riskLevel: "Low",
    status: "Estimate Scheduled",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "12",
    jobNumber: "J-1012",
    customerName: "George Harris",
    phone: "865-555-0112",
    email: "george.h@example.com",
    address: "909 Maple Dr",
    city: "Louisville",
    flooringType: "Laminate",
    rooms: [{ id: "r12", name: "Basement", length: 40, width: 20 }],
    squareFootage: 800,
    crewAssigned: "Crew A",
    estStartDate: "2023-12-05",
    estCompletionDate: "2023-12-06",
    materialStatus: "Delayed",
    laborEstimate: 2000,
    materialEstimate: 2100,
    estRevenue: 6500,
    estGrossProfit: 2400,
    grossMarginPct: 36.9,
    notes: "Material on backorder.",
    priorityLevel: "Medium",
    riskLevel: "Medium",
    status: "Material Ordered",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "13",
    jobNumber: "J-1013",
    customerName: "Linda Clark",
    phone: "865-555-0113",
    email: "linda.c@example.com",
    address: "1010 Walnut St",
    city: "Loudon",
    flooringType: "Hardwood",
    rooms: [{ id: "r13", name: "Living & Dining", length: 35, width: 20 }],
    squareFootage: 700,
    crewAssigned: "Crew C",
    estStartDate: "2023-11-27",
    estCompletionDate: "2023-11-29",
    materialStatus: "Received",
    laborEstimate: 2800,
    materialEstimate: 4200,
    estRevenue: 10500,
    estGrossProfit: 3500,
    grossMarginPct: 33.3,
    notes: "Matching existing hallway.",
    priorityLevel: "High",
    riskLevel: "Medium",
    status: "Scheduled",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "14",
    jobNumber: "J-1014",
    customerName: "Robert Lewis",
    phone: "865-555-0114",
    email: "robert.l@example.com",
    address: "1111 Chestnut Ln",
    city: "Bearden",
    flooringType: "Tile",
    rooms: [{ id: "r14", name: "Master Bath", length: 15, width: 10 }],
    squareFootage: 150,
    crewAssigned: "Crew D",
    estStartDate: "2023-11-22",
    estCompletionDate: "2023-11-24",
    materialStatus: "In Transit",
    laborEstimate: 900,
    materialEstimate: 800,
    estRevenue: 2800,
    estGrossProfit: 1100,
    grossMarginPct: 39.2,
    notes: "Custom mosaic pattern.",
    priorityLevel: "Medium",
    riskLevel: "High",
    status: "Scheduled",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "15",
    jobNumber: "J-1015",
    customerName: "Barbara Young",
    phone: "865-555-0115",
    email: "barbara.y@example.com",
    address: "1212 Ash Blvd",
    city: "West Knoxville",
    flooringType: "Luxury Vinyl Plank (LVP)",
    rooms: [{ id: "r15", name: "Entire Upstairs", length: 60, width: 30 }],
    squareFootage: 1800,
    crewAssigned: "Crew A",
    estStartDate: "2023-11-10",
    estCompletionDate: "2023-11-13",
    materialStatus: "Received",
    laborEstimate: 4500,
    materialEstimate: 6000,
    estRevenue: 15000,
    estGrossProfit: 4500,
    grossMarginPct: 30.0,
    actualRevenue: 15000,
    actualLaborCost: 6800,
    actualMaterialCost: 8200,
    actualAddOnCost: 600,
    notes: "Subfloor might need leveling.",
    priorityLevel: "Medium",
    riskLevel: "Medium",
    status: "Final Walkthrough",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "16",
    jobNumber: "J-1016",
    customerName: "Paul King",
    phone: "865-555-0116",
    email: "paul.k@example.com",
    address: "1313 Hickory Rd",
    city: "Karns",
    flooringType: "Carpet",
    rooms: [{ id: "r16", name: "Living Room", length: 20, width: 15 }],
    squareFootage: 300,
    crewAssigned: "Crew B",
    estStartDate: "2023-11-18",
    estCompletionDate: "2023-11-18",
    materialStatus: "Received",
    laborEstimate: 450,
    materialEstimate: 900,
    estRevenue: 2000,
    estGrossProfit: 650,
    grossMarginPct: 32.5,
    actualRevenue: 2000,
    actualLaborCost: 720,
    actualMaterialCost: 1180,
    actualAddOnCost: 0,
    notes: "Quick job, fit into afternoon.",
    priorityLevel: "Low",
    riskLevel: "Low",
    status: "In Progress",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "17",
    jobNumber: "J-1017",
    customerName: "Nancy Wright",
    phone: "865-555-0117",
    email: "nancy.w@example.com",
    address: "1414 Poplar Ave",
    city: "Halls",
    flooringType: "Hardwood",
    rooms: [{ id: "r17", name: "Dining Room", length: 25, width: 20 }],
    squareFootage: 500,
    crewAssigned: "Crew C",
    materialStatus: "Missing Items",
    laborEstimate: 2000,
    materialEstimate: 3000,
    estRevenue: 7500,
    estGrossProfit: 2500,
    grossMarginPct: 33.3,
    notes: "Missing transition strips.",
    priorityLevel: "High",
    riskLevel: "High",
    status: "Approved",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "18",
    jobNumber: "J-1018",
    customerName: "Kevin Scott",
    phone: "865-555-0118",
    email: "kevin.s@example.com",
    address: "1515 Sycamore Dr",
    city: "Fountain City",
    flooringType: "Commercial LVT",
    rooms: [{ id: "r18", name: "Retail Space", length: 50, width: 50 }],
    squareFootage: 2500,
    crewAssigned: "Crew A",
    estStartDate: "2023-10-15",
    estCompletionDate: "2023-10-18",
    materialStatus: "Received",
    laborEstimate: 7500,
    materialEstimate: 10000,
    estRevenue: 28000,
    estGrossProfit: 10500,
    grossMarginPct: 37.5,
    actualRevenue: 28250,
    actualLaborCost: 7900,
    actualMaterialCost: 10100,
    actualAddOnCost: 600,
    notes: "Completed last month.",
    priorityLevel: "Low",
    riskLevel: "Low",
    status: "Invoiced",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "19",
    jobNumber: "J-1019",
    customerName: "Betty Green",
    phone: "865-555-0119",
    email: "betty.g@example.com",
    address: "1616 Elm St",
    city: "Pigeon Forge",
    flooringType: "Tile",
    rooms: [{ id: "r19", name: "Kitchen", length: 20, width: 20 }],
    squareFootage: 400,
    crewAssigned: "Unassigned",
    materialStatus: "Ordered",
    laborEstimate: 2000,
    materialEstimate: 1800,
    estRevenue: 6000,
    estGrossProfit: 2200,
    grossMarginPct: 36.6,
    notes: "Cabin rental, hard to reach.",
    priorityLevel: "Medium",
    riskLevel: "High",
    status: "Proposal Sent",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "20",
    jobNumber: "J-1020",
    customerName: "Mark Baker",
    phone: "865-555-0120",
    email: "mark.b@example.com",
    address: "1717 Spruce Way",
    city: "Maryville",
    flooringType: "Luxury Vinyl Plank (LVP)",
    rooms: [{ id: "r20", name: "Basement", length: 40, width: 25 }],
    squareFootage: 1000,
    crewAssigned: "Unassigned",
    materialStatus: "Ordered",
    laborEstimate: 2500,
    materialEstimate: 3500,
    estRevenue: 9500,
    estGrossProfit: 3500,
    grossMarginPct: 36.8,
    notes: "Just signed.",
    priorityLevel: "Low",
    riskLevel: "Low",
    status: "New Lead",
    createdAt: now,
    updatedAt: now,
  },
];

export const SEED_MATERIALS: MaterialInsert[] = [
  {
    id: "m1",
    jobId: "1",
    jobNumber: "J-1001",
    customer: "Sarah Thompson",
    city: "Farragut",
    flooringType: "Luxury Vinyl Plank (LVP)",
    supplier: "COREtec",
    orderedDate: "2023-10-15",
    expectedDeliveryDate: "2023-10-30",
    actualDeliveryDate: "2023-10-28",
    received: true,
    damaged: false,
    missingItems: "",
    notes: "All materials accounted for.",
    status: "Received",
  },
  {
    id: "m2",
    jobId: "2",
    jobNumber: "J-1002",
    customer: "Mike Reynolds",
    city: "Maryville",
    flooringType: "Carpet",
    supplier: "Shaw Floors",
    orderedDate: "2023-10-25",
    expectedDeliveryDate: "2023-11-05",
    received: false,
    damaged: false,
    missingItems: "",
    notes: "In transit from GA warehouse.",
    status: "In Transit",
  },
  {
    id: "m3",
    jobId: "3",
    jobNumber: "J-1003",
    customer: "Amy Carter",
    city: "Oak Ridge",
    flooringType: "Hardwood",
    supplier: "Bruce Hardwood",
    orderedDate: "2023-11-01",
    expectedDeliveryDate: "2023-11-15",
    received: false,
    damaged: false,
    missingItems: "",
    notes: "Needs 72hr acclimation upon delivery.",
    status: "Ordered",
  },
  {
    id: "m5",
    jobId: "5",
    jobNumber: "J-1005",
    customer: "Jason Miller",
    city: "Sevierville",
    flooringType: "Tile",
    supplier: "Daltile",
    orderedDate: "2023-10-20",
    expectedDeliveryDate: "2023-11-02",
    received: false,
    damaged: false,
    missingItems: "",
    notes: "Delayed due to backorder on specific grout color.",
    status: "Delayed",
  },
  {
    id: "m4",
    jobId: "4",
    jobNumber: "J-1004",
    customer: "Green Valley Dental",
    city: "Knoxville",
    flooringType: "Commercial LVT",
    supplier: "Mannington",
    orderedDate: "2023-10-10",
    expectedDeliveryDate: "2023-10-22",
    actualDeliveryDate: "2023-10-21",
    received: true,
    damaged: false,
    missingItems: "",
    notes: "Commercial grade, all pallets received.",
    status: "Received",
  },
  {
    id: "m7",
    jobId: "7",
    jobNumber: "J-1007",
    customer: "David Morgan",
    city: "Alcoa",
    flooringType: "Laminate",
    supplier: "Mohawk",
    orderedDate: "2023-09-28",
    expectedDeliveryDate: "2023-10-08",
    actualDeliveryDate: "2023-10-07",
    received: true,
    damaged: false,
    missingItems: "",
    notes: "Delivered ahead of schedule.",
    status: "Received",
  },
  {
    id: "m8",
    jobId: "8",
    jobNumber: "J-1008",
    customer: "Summit Church Office",
    city: "Powell",
    flooringType: "Commercial Carpet Tile",
    supplier: "Engineered Floors",
    orderedDate: "2023-11-02",
    expectedDeliveryDate: "2023-11-18",
    received: false,
    damaged: false,
    missingItems: "",
    notes: "Large commercial order, partial shipment expected.",
    status: "In Transit",
  },
  {
    id: "m9",
    jobId: "9",
    jobNumber: "J-1009",
    customer: "Karen Wilson",
    city: "Tellico Village",
    flooringType: "Hardwood",
    supplier: "Southwind",
    orderedDate: "2023-10-18",
    expectedDeliveryDate: "2023-11-01",
    actualDeliveryDate: "2023-11-01",
    received: true,
    damaged: true,
    missingItems: "",
    notes: "Two cartons arrived with water damage. Replacement requested.",
    status: "Damaged",
  },
  {
    id: "m10",
    jobId: "10",
    jobNumber: "J-1010",
    customer: "Rob Jenkins",
    city: "Hardin Valley",
    flooringType: "Luxury Vinyl Plank (LVP)",
    supplier: "MSI Surfaces",
    orderedDate: "2023-10-22",
    expectedDeliveryDate: "2023-11-04",
    actualDeliveryDate: "2023-11-04",
    received: true,
    damaged: false,
    missingItems: "Stair nose transitions (4) and color-matched quarter round.",
    notes: "Main planks received; trim accessories missing from shipment.",
    status: "Missing Items",
  },
];

export const SEED_PROPOSALS: ProposalInsert[] = [
  ...GENERATED_PROPOSALS,
  {
    id: "p1",
    jobId: "6",
    customerName: "Brenda Wallace",
    projectLocation: "303 River Rd, Lenoir City",
    flooringType: "Waterproof Flooring",
    roomList: [{ id: "r6", name: "Basement", length: 33, width: 33.33 }],
    totalSqFt: 1100,
    scopeOfWork:
      "Remove existing carpet, prep subfloor, install waterproof LVP in basement, and install base shoe molding.",
    estimatedPrice: 10400,
    expectedTimeline: "2 days",
    materialAssumptions: "COREtec Advanced Plus, standard transitions.",
    exclusions: 'Major subfloor leveling exceeding 1/4" variance, plumbing moves.',
    warrantyNote:
      "Lifetime residential limited warranty on material, 1-year labor warranty.",
    depositType: "percent",
    depositValue: 50,
    paymentTerms: "50% deposit to schedule, balance due on completion.",
    status: "Sent",
    shareToken: "quotebrendawallace1",
    sentAt: now,
    createdAt: now,
  },
  {
    id: "p2",
    customerName: "Marcus Tran",
    projectLocation: "84 Cedar Bluff Way, Knoxville",
    flooringType: "Hardwood",
    roomList: [
      { id: "r7", name: "Living Room", length: 20, width: 18 },
      { id: "r8", name: "Hallway", length: 16, width: 5 },
    ],
    totalSqFt: 440,
    scopeOfWork:
      "Install 3/4\" white oak hardwood in living room and hallway, sand and finish on site, install matching transitions.",
    estimatedPrice: 7600,
    expectedTimeline: "4 days",
    materialAssumptions: "Select-grade white oak, satin polyurethane finish.",
    exclusions: "Furniture moving, baseboard replacement.",
    warrantyNote: "1-year installation warranty.",
    depositType: "amount",
    depositValue: 2000,
    paymentTerms: "$2,000 deposit, balance net 15 after completion.",
    status: "Accepted",
    shareToken: "quotemarcustran2",
    sentAt: now,
    viewedAt: now,
    acceptedAt: now,
    signature: "Marcus Tran",
    createdAt: now,
  },
];

export const SEED_SALESPEOPLE: SalespersonInsert[] = [
  {
    id: "sp1",
    name: "Will Hedley",
    email: "will@knoxvilleflooringcenter.com",
    phone: "865-555-0000",
    active: true,
    color: "#2563eb",
    createdAt: now,
  },
  {
    id: "sp2",
    name: "Dana Mitchell",
    email: "dana@knoxvilleflooringcenter.com",
    phone: "865-555-0011",
    active: true,
    commissionRate: 7,
    color: "#db2777",
    createdAt: now,
  },
  {
    id: "sp3",
    name: "Carlos Vega",
    email: "carlos@knoxvilleflooringcenter.com",
    phone: "865-555-0012",
    active: true,
    commissionRate: 6,
    color: "#16a34a",
    createdAt: now,
  },
  {
    id: "sp4",
    name: "Brittany Cole",
    email: "brittany@knoxvilleflooringcenter.com",
    phone: "865-555-0013",
    active: true,
    color: "#d97706",
    createdAt: now,
  },
];

function taskTime(dayOffset: number, hour: number, minutes = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, minutes, 0, 0);
  return d.toISOString();
}

export const SEED_TASKS: TaskInsert[] = [
  {
    id: "task1",
    title: "Site measure — Thompson kitchen",
    description: "Confirm subfloor condition and bring LVP samples.",
    assigneeId: "sp1",
    startAt: taskTime(0, 9),
    endAt: taskTime(0, 10, 30),
    allDay: false,
    status: "Open",
    relatedJobId: "1",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task2",
    title: "Follow up with Dana's quoted leads",
    description: "Call back the three quotes sent last week.",
    assigneeId: "sp2",
    startAt: taskTime(1, 13),
    endAt: taskTime(1, 14),
    allDay: false,
    status: "Open",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task3",
    title: "Order hardwood for Morgan job",
    description: "Place supplier order; 320 sq ft white oak.",
    assigneeId: "sp3",
    startAt: taskTime(2, 11),
    endAt: taskTime(2, 11, 30),
    allDay: false,
    status: "Open",
    relatedJobId: "7",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task4",
    title: "Showroom restock & display refresh",
    description: "Rotate new carpet samples to the front.",
    assigneeId: "sp4",
    startAt: taskTime(-1, 8),
    endAt: taskTime(-1, 9),
    allDay: false,
    status: "Done",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task5",
    title: "Team install planning",
    description: "Review the week's install schedule with crews.",
    assigneeId: "sp1",
    startAt: taskTime(3, 0),
    endAt: taskTime(3, 0),
    allDay: true,
    status: "Open",
    createdAt: now,
    updatedAt: now,
  },
];

export const SEED_INVOICES: InvoiceInsert[] = [
  ...GENERATED_INVOICES,
  {
    id: "inv1",
    invoiceNumber: "INV-1001",
    jobId: "7",
    jobNumber: "J-1007",
    customerName: "David Morgan",
    lineItems: [
      { id: "li1", description: "Installation labor", category: "Labor", quantity: 1, unitPrice: 3250 },
      { id: "li2", description: "Hardwood flooring & supplies", category: "Materials", quantity: 1, unitPrice: 3500 },
      { id: "li3", description: "Furniture moving", category: "Add-on", quantity: 1, unitPrice: 500 },
    ],
    subtotal: 7250,
    total: 7250,
    status: "Paid",
    issueDate: daysFromNow(-30),
    dueDate: daysFromNow(-15),
    notes: "Thank you for your business!",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "inv2",
    invoiceNumber: "INV-1002",
    jobId: "13",
    jobNumber: "J-1013",
    customerName: "Linda Clark",
    lineItems: [
      { id: "li1", description: "Installation labor", category: "Labor", quantity: 1, unitPrice: 4000 },
      { id: "li2", description: "LVP flooring & underlayment", category: "Materials", quantity: 1, unitPrice: 6000 },
      { id: "li3", description: "Quarter-round molding", category: "Add-on", quantity: 1, unitPrice: 500 },
    ],
    subtotal: 10500,
    total: 10500,
    status: "Paid",
    issueDate: daysFromNow(-20),
    dueDate: daysFromNow(-5),
    notes: "",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "inv3",
    invoiceNumber: "INV-1003",
    jobId: "4",
    jobNumber: "J-1004",
    customerName: "Green Valley Dental",
    lineItems: [
      { id: "li1", description: "Commercial installation labor", category: "Labor", quantity: 1, unitPrice: 12000 },
      { id: "li2", description: "Commercial LVT & adhesives", category: "Materials", quantity: 1, unitPrice: 18000 },
      { id: "li3", description: "After-hours scheduling", category: "Add-on", quantity: 1, unitPrice: 1500 },
    ],
    subtotal: 31500,
    total: 31500,
    status: "Sent",
    issueDate: daysFromNow(-7),
    dueDate: daysFromNow(23),
    notes: "Net 30 terms.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "inv4",
    invoiceNumber: "INV-1004",
    jobId: "1",
    jobNumber: "J-1001",
    customerName: "Sarah Thompson",
    lineItems: [
      { id: "li1", description: "Installation labor", category: "Labor", quantity: 1, unitPrice: 5000 },
      { id: "li2", description: "Luxury vinyl plank & underlayment", category: "Materials", quantity: 1, unitPrice: 6000 },
      { id: "li3", description: "Quiet underlayment upgrade", category: "Add-on", quantity: 1, unitPrice: 850 },
    ],
    subtotal: 11850,
    total: 11850,
    status: "Overdue",
    issueDate: daysFromNow(-45),
    dueDate: daysFromNow(-15),
    notes: "Reminder sent.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "inv5",
    invoiceNumber: "INV-1005",
    jobId: "15",
    jobNumber: "J-1015",
    customerName: "Barbara Young",
    lineItems: [
      { id: "li1", description: "Installation labor", category: "Labor", quantity: 1, unitPrice: 6500 },
      { id: "li2", description: "Hardwood flooring & supplies", category: "Materials", quantity: 1, unitPrice: 8000 },
      { id: "li3", description: "Stair nosing", category: "Add-on", quantity: 1, unitPrice: 500 },
    ],
    subtotal: 15000,
    total: 15000,
    status: "Overdue",
    issueDate: daysFromNow(-40),
    dueDate: daysFromNow(-10),
    notes: "",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "inv6",
    invoiceNumber: "INV-1006",
    jobId: "8",
    jobNumber: "J-1008",
    customerName: "Summit Church Office",
    lineItems: [
      { id: "li1", description: "Commercial installation labor", category: "Labor", quantity: 1, unitPrice: 6000 },
      { id: "li2", description: "Commercial carpet tile", category: "Materials", quantity: 1, unitPrice: 22000 },
      { id: "li3", description: "Old flooring disposal", category: "Add-on", quantity: 1, unitPrice: 1600 },
    ],
    subtotal: 29600,
    total: 29600,
    status: "Draft",
    issueDate: daysFromNow(0),
    dueDate: daysFromNow(30),
    notes: "Awaiting final walkthrough sign-off.",
    createdAt: now,
    updatedAt: now,
  },
];

export const SEED_PRODUCTS: ProductInsert[] = [
  ...GENERATED_PRODUCTS,
  {
    id: "prod1",
    name: "Coretec Pro Plus 7\" Oak",
    category: "Vinyl Plank",
    sku: "CP-7OAK-NAT",
    supplier: "Shaw Industries",
    color: "Natural Oak",
    unit: "sqft",
    cost: 2.15,
    price: 4.49,
    quantityOnHand: 4200,
    inventoryType: "Inventory",
    active: true,
    notes: "Best-selling waterproof rigid core plank.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod2",
    name: "LifeProof Sterling Oak LVP",
    category: "Vinyl Plank",
    sku: "LP-STR-OAK",
    supplier: "Home Decorators",
    color: "Sterling Oak",
    unit: "sqft",
    cost: 1.79,
    price: 3.29,
    quantityOnHand: 3100,
    inventoryType: "Inventory",
    active: true,
    notes: "",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod3",
    name: "Armstrong Alterna Luxury Vinyl Tile",
    category: "Vinyl Tile",
    sku: "AA-LVT-SLATE",
    supplier: "Armstrong",
    color: "Slate Gray",
    unit: "box",
    cost: 38.0,
    price: 72.0,
    quantityOnHand: 48,
    inventoryType: "Inventory",
    active: true,
    notes: "Groutable LVT, 25 sqft per box.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod4",
    name: "Mohawk SmartStrand Plush Carpet",
    category: "Carpet",
    sku: "MH-SS-BEIGE",
    supplier: "Mohawk",
    color: "Warm Beige",
    unit: "sqft",
    cost: 1.95,
    price: 3.99,
    quantityOnHand: 1800,
    inventoryType: "Inventory",
    active: true,
    notes: "Stain-resistant residential carpet, 12' roll.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod5",
    name: "Shaw Berber Loop Carpet",
    category: "Carpet",
    sku: "SH-BRB-GRY",
    supplier: "Shaw Industries",
    color: "Pewter",
    unit: "sqft",
    cost: 1.45,
    price: 2.89,
    quantityOnHand: 90,
    inventoryType: "Inventory",
    active: true,
    notes: "Low stock - reorder soon.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod6",
    name: "Bruce Solid Oak Hardwood 3/4\"",
    category: "Hardwood",
    sku: "BR-OAK-GUNSTK",
    supplier: "Bruce",
    color: "Gunstock",
    unit: "sqft",
    cost: 4.25,
    price: 7.99,
    quantityOnHand: 2400,
    inventoryType: "Inventory",
    active: true,
    notes: "Solid 3/4\" red oak, site-finished or prefinished.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod7",
    name: "Mirage Maple Engineered Hardwood",
    category: "Hardwood",
    sku: "MIR-MPL-NAT",
    supplier: "Mirage",
    color: "Natural Maple",
    unit: "sqft",
    cost: 5.6,
    price: 9.49,
    quantityOnHand: 0,
    inventoryType: "Special Order",
    active: true,
    notes: "Special order only - 2-3 week lead time.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod8",
    name: "Daltile Marble Look Porcelain 12x24",
    category: "Tile",
    sku: "DT-PORC-CARRARA",
    supplier: "Daltile",
    color: "Carrara White",
    unit: "box",
    cost: 28.0,
    price: 54.0,
    quantityOnHand: 65,
    inventoryType: "Inventory",
    active: true,
    notes: "Rectified porcelain, 15.6 sqft per box.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod9",
    name: "MSI Hexagon Mosaic Tile",
    category: "Tile",
    sku: "MSI-HEX-WHT",
    supplier: "MSI",
    color: "Glossy White",
    unit: "box",
    cost: 9.5,
    price: 18.99,
    quantityOnHand: 120,
    inventoryType: "Inventory",
    active: true,
    notes: "Accent / bathroom floor mosaic.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod10",
    name: "Pergo Outlast+ Laminate",
    category: "Laminate",
    sku: "PG-OUT-VINTAGE",
    supplier: "Pergo",
    color: "Vintage Pewter Oak",
    unit: "sqft",
    cost: 1.65,
    price: 3.19,
    quantityOnHand: 2750,
    inventoryType: "Inventory",
    active: true,
    notes: "Water-resistant laminate with attached pad.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod11",
    name: "Aquaguard Waterproof Laminate",
    category: "Waterproof",
    sku: "AQ-WPL-DRIFT",
    supplier: "Floor & Decor",
    color: "Driftwood",
    unit: "sqft",
    cost: 2.05,
    price: 3.79,
    quantityOnHand: 1500,
    inventoryType: "Inventory",
    active: true,
    notes: "100% waterproof, suitable for basements.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod12",
    name: "Interface Commercial Carpet Tile",
    category: "Commercial",
    sku: "INT-CT-CHARCOAL",
    supplier: "Interface",
    color: "Charcoal",
    unit: "box",
    cost: 42.0,
    price: 78.0,
    quantityOnHand: 30,
    inventoryType: "Inventory",
    active: true,
    notes: "Modular carpet tile, 20 sqft per box, heavy traffic.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod13",
    name: "Mannington Commercial LVT Plank",
    category: "Commercial",
    sku: "MAN-CLVT-WALNUT",
    supplier: "Mannington",
    color: "Walnut",
    unit: "box",
    cost: 36.0,
    price: 68.0,
    quantityOnHand: 22,
    inventoryType: "Inventory",
    active: true,
    notes: "20 mil wear layer, commercial warranty.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod14",
    name: "Quarter Round Molding - Oak",
    category: "Trim/Supplies",
    sku: "TR-QR-OAK",
    supplier: "Shaw Industries",
    color: "Natural Oak",
    unit: "lineal ft",
    cost: 0.75,
    price: 1.89,
    quantityOnHand: 900,
    inventoryType: "Inventory",
    active: true,
    notes: "Color-matched quarter round, 8' lengths.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod15",
    name: "T-Molding Transition Strip",
    category: "Trim/Supplies",
    sku: "TR-TMOLD-GRY",
    supplier: "Generic",
    color: "Gray Oak",
    unit: "each",
    cost: 6.5,
    price: 14.99,
    quantityOnHand: 140,
    inventoryType: "Inventory",
    active: true,
    notes: "Floor-to-floor transition, 94\" length.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod16",
    name: "Premium Underlayment Foam Roll",
    category: "Trim/Supplies",
    sku: "TR-UND-FOAM",
    supplier: "Floor & Decor",
    color: "Blue",
    unit: "sqft",
    cost: 0.18,
    price: 0.49,
    quantityOnHand: 6000,
    inventoryType: "Inventory",
    active: true,
    notes: "Moisture-barrier underlayment for floating floors.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod17",
    name: "Schluter Ditra Uncoupling Membrane",
    category: "Trim/Supplies",
    sku: "TR-DITRA",
    supplier: "Schluter",
    color: "Orange",
    unit: "sqft",
    cost: 1.35,
    price: 2.79,
    quantityOnHand: 40,
    inventoryType: "Inventory",
    active: true,
    notes: "Tile crack-isolation membrane.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod18",
    name: "Karndean Designflooring Herringbone",
    category: "Vinyl Plank",
    sku: "KD-HB-SMOKED",
    supplier: "Karndean",
    color: "Smoked Oak",
    unit: "sqft",
    cost: 3.95,
    price: 7.49,
    quantityOnHand: 0,
    inventoryType: "Special Order",
    active: true,
    notes: "Designer herringbone pattern, special order.",
    createdAt: now,
    updatedAt: now,
  },
];

export const SEED_SETTINGS: SettingsInsert = {
  id: 1,
  ownerName: "Will Hedley",
  ownerRole: "Owner",
  companyName: "Knoxville Flooring Center",
  address: "100 Flooring Way, Knoxville, TN 37901",
  phone: "865-555-0000",
  email: "info@knoxvilleflooringcenter.com",
  website: "www.knoxvilleflooringcenter.com",
  defaultWasteFactor: 10,
  defaultLaborRateLVP: 2.5,
  defaultLaborRateHardwood: 4.0,
  defaultLaborRateCarpet: 1.5,
  defaultLaborRateTile: 5.0,
  commissionBasis: "Gross Profit",
  defaultCommissionRate: 5,
};

const today = new Date();
const dateOffset = (days: number): string => {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

export const SEED_LEADS: LeadInsert[] = [
  ...GENERATED_LEADS,
  {
    id: "lead-demo",
    customerName: "Marcus & Elena Whitfield",
    phone: "865-555-0147",
    email: "whitfield.home@example.com",
    address: "1131 Armstrong Ave",
    city: "Knoxville",
    flooringInterest: "Hardwood",
    estimatedValue: 21800,
    source: "Referral",
    stage: "New",
    salesperson: "Will Knox",
    followUpDate: dateOffset(2),
    company: "",
    contactType: "Residential",
    branch: "Knoxville Main",
    mainPhone: "865-555-0147",
    spousePhone: "865-555-0148",
    ccEmail: "elena.whitfield@example.com",
    desiredServices: "Tear-out, subfloor prep, white oak hardwood install, stair treads",
    estimatedSqft: 1850,
    interestLevel: "Hot",
    installRequest: "Looking to start within 4-6 weeks, before holidays",
    leadCost: 95,
    financingAmount: 12000,
    taxExempt: false,
    addressTitle: "Primary Residence",
    street: "1131 Armstrong Ave",
    state: "TN",
    zip: "37917",
    county: "Knox",
    subdivision: "Parkridge",
    sortOrder: 0,
    activityLog: [
      {
        id: "demo-act-1",
        date: dateOffset(-5),
        type: "Note",
        note: "Referred by neighbor. Renovating 1920s home, wants period-appropriate white oak.",
      },
      {
        id: "demo-act-2",
        date: dateOffset(-3),
        type: "Call",
        note: "Discussed scope: main floor + stairs. Sent inspiration gallery.",
      },
    ],
    noteEntries: [
      {
        id: "demo-note-1",
        body: "Home is a historic Parkridge bungalow. Existing floors are original pine, badly worn. Couple wants 4\" white oak, natural matte finish to match era.",
        author: "Will Knox",
        createdAt: dateOffset(-5),
      },
      {
        id: "demo-note-2",
        body: "Elena prefers low-VOC finishes (newborn in home). Recommend waterborne poly.",
        author: "Will Knox",
        createdAt: dateOffset(-3),
      },
    ],
    contacts: [
      {
        id: "demo-contact-1",
        name: "Marcus Whitfield",
        role: "Homeowner",
        phone: "865-555-0147",
        email: "whitfield.home@example.com",
        notes: "Primary decision maker, works from home — daytime calls OK.",
        createdAt: dateOffset(-5),
      },
      {
        id: "demo-contact-2",
        name: "Elena Whitfield",
        role: "Co-owner / Spouse",
        phone: "865-555-0148",
        email: "elena.whitfield@example.com",
        notes: "Handles finish + color selections.",
        createdAt: dateOffset(-5),
      },
    ],
    addresses: [
      {
        id: "demo-addr-1",
        title: "Primary Residence",
        street: "1131 Armstrong Ave",
        city: "Knoxville",
        state: "TN",
        zip: "37917",
        county: "Knox",
        subdivision: "Parkridge",
        isPrimary: true,
        createdAt: dateOffset(-5),
      },
    ],
    samples: [
      {
        id: "demo-sample-1",
        productName: "White Oak 4\" Plank",
        color: "Natural Matte",
        sku: "WO-4-NAT",
        status: "Checked Out",
        checkedOutDate: dateOffset(-3),
        returnDate: dateOffset(4),
        notes: "Left two finish samples with homeowner to view in daylight.",
        createdAt: dateOffset(-3),
      },
    ],
    tasks: [
      {
        id: "demo-task-1",
        title: "Schedule in-home measurement",
        dueDate: dateOffset(2),
        assignedTo: "Will Knox",
        completed: false,
        createdAt: dateOffset(-3),
      },
      {
        id: "demo-task-2",
        title: "Email low-VOC finish options",
        dueDate: dateOffset(-1),
        assignedTo: "Will Knox",
        completed: true,
        completedAt: dateOffset(-1),
        createdAt: dateOffset(-3),
      },
    ],
    interactions: [
      {
        id: "demo-int-1",
        type: "Phone Call",
        summary: "20-min intro call, reviewed scope and rough budget range $18k-24k.",
        date: dateOffset(-3),
        createdAt: dateOffset(-3),
      },
      {
        id: "demo-int-2",
        type: "Showroom Visit",
        summary: "Couple visited showroom, narrowed to white oak natural matte.",
        date: dateOffset(-2),
        createdAt: dateOffset(-2),
      },
    ],
    documents: [],
    measurements: [
      {
        id: "demo-meas-1",
        label: "Main Floor (prelim)",
        totalSqft: 1620,
        rooms: 5,
        measuredDate: dateOffset(-2),
        source: "Estimate",
        notes: "Living, dining, hall, two bedrooms. Stairs measured separately.",
        createdAt: dateOffset(-2),
      },
    ],
    notes: "High-intent referral. Historic home, premium white oak, low-VOC finish. Strong close potential.",
    createdAt: dateOffset(-5),
    updatedAt: dateOffset(-2),
  },
  {
    id: "lead-1",
    customerName: "Jennifer Walsh",
    phone: "865-555-0201",
    email: "jen.walsh@example.com",
    address: "742 Maple Grove Dr",
    city: "Farragut",
    flooringInterest: "Hardwood",
    estimatedValue: 14500,
    source: "Referral",
    stage: "New",
    salesperson: "Will Knox",
    followUpDate: dateOffset(-2),
    activityLog: [
      {
        id: "act-1",
        date: dateOffset(-4),
        type: "Note",
        note: "Inbound call — interested in white oak hardwood for main floor.",
      },
    ],
    notes: "Referred by Sarah Thompson (J-1001). Wants premium look.",
    createdAt: dateOffset(-4),
    updatedAt: dateOffset(-4),
  },
  {
    id: "lead-2",
    customerName: "Carlos Mendez",
    phone: "865-555-0202",
    email: "carlos.m@example.com",
    address: "318 Riverbend Ave",
    city: "Knoxville",
    flooringInterest: "Luxury Vinyl Plank (LVP)",
    estimatedValue: 8200,
    source: "Website",
    stage: "Contacted",
    salesperson: "Will Knox",
    followUpDate: dateOffset(0),
    activityLog: [
      {
        id: "act-2",
        date: dateOffset(-6),
        type: "Note",
        note: "Submitted website quote form for kitchen + hallway.",
      },
      {
        id: "act-3",
        date: dateOffset(-3),
        type: "Call",
        note: "Left voicemail, sent intro text.",
      },
    ],
    notes: "Budget-conscious. Comparing 2-3 contractors.",
    createdAt: dateOffset(-6),
    updatedAt: dateOffset(-3),
  },
  {
    id: "lead-3",
    customerName: "Patricia Nguyen",
    phone: "865-555-0203",
    email: "p.nguyen@example.com",
    address: "55 Highland Park Rd",
    city: "Maryville",
    flooringInterest: "Tile",
    estimatedValue: 11200,
    source: "Walk-in",
    stage: "Estimate Scheduled",
    salesperson: "Dana Reed",
    followUpDate: dateOffset(3),
    activityLog: [
      {
        id: "act-4",
        date: dateOffset(-8),
        type: "Note",
        note: "Visited showroom, loved porcelain tile samples.",
      },
      {
        id: "act-5",
        date: dateOffset(-2),
        type: "Stage Change",
        note: "Booked in-home estimate.",
      },
    ],
    notes: "Master bath + entryway. Wants heated floor option priced.",
    createdAt: dateOffset(-8),
    updatedAt: dateOffset(-2),
  },
  {
    id: "lead-4",
    customerName: "Greg Holloway",
    phone: "865-555-0204",
    email: "greg.h@example.com",
    address: "1290 Lakeshore Blvd",
    city: "Lenoir City",
    flooringInterest: "Carpet",
    estimatedValue: 6400,
    source: "Phone Call",
    stage: "Quoted",
    salesperson: "Dana Reed",
    followUpDate: dateOffset(1),
    activityLog: [
      {
        id: "act-6",
        date: dateOffset(-12),
        type: "Note",
        note: "Called about bedroom carpet replacement.",
      },
      {
        id: "act-7",
        date: dateOffset(-5),
        type: "Email",
        note: "Sent written quote for 3 bedrooms.",
      },
    ],
    notes: "Deciding between two carpet grades. Follow up on decision.",
    createdAt: dateOffset(-12),
    updatedAt: dateOffset(-5),
  },
  {
    id: "lead-5",
    customerName: "Amanda Foster",
    phone: "865-555-0205",
    email: "amanda.f@example.com",
    address: "907 Sequoyah Hills Pl",
    city: "Knoxville",
    flooringInterest: "Waterproof Flooring",
    estimatedValue: 9800,
    source: "Social Media",
    stage: "Won",
    salesperson: "Will Knox",
    activityLog: [
      {
        id: "act-8",
        date: dateOffset(-20),
        type: "Note",
        note: "Instagram DM about basement waterproof flooring.",
      },
      {
        id: "act-9",
        date: dateOffset(-7),
        type: "Stage Change",
        note: "Accepted proposal — converting to job.",
      },
    ],
    notes: "Closed! Basement rec room, ~1100 sq ft.",
    createdAt: dateOffset(-20),
    updatedAt: dateOffset(-7),
  },
  {
    id: "lead-6",
    customerName: "Robert Chen",
    phone: "865-555-0206",
    email: "rob.chen@example.com",
    address: "44 Old Mill Ct",
    city: "Oak Ridge",
    flooringInterest: "Laminate",
    estimatedValue: 5200,
    source: "Home Show",
    stage: "Lost",
    salesperson: "Dana Reed",
    lostReason: "Went with a lower-priced competitor.",
    activityLog: [
      {
        id: "act-10",
        date: dateOffset(-25),
        type: "Note",
        note: "Met at Knoxville Home & Garden Show.",
      },
      {
        id: "act-11",
        date: dateOffset(-10),
        type: "Stage Change",
        note: "Lost — chose competitor on price.",
      },
    ],
    notes: "Price sensitive. Revisit for future projects.",
    createdAt: dateOffset(-25),
    updatedAt: dateOffset(-10),
  },
];

// Full ISO timestamp `days` ago at an approximate hour — used so seeded
// communications sort sensibly newest-first in the history view.
const dateTimeOffset = (days: number, hour = 10, minute = 0): string => {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};

const ck = (name: string): string =>
  encodeURIComponent(name.trim().toLowerCase().replace(/\s+/g, " "));

const KNOX_EMAIL = "Knox Flooring <onboarding@resend.dev>";
const KNOX_SMS = "+18655550100";

// Illustrative demo conversations. These are NOT sent through any provider;
// they exist only to populate the communications history for demo leads.
export const SEED_COMMUNICATIONS: CommunicationInsert[] = [
  // Jennifer Walsh (lead-1) — email thread + SMS reminder
  {
    id: "comm-1",
    leadId: "lead-1",
    customerKey: ck("Jennifer Walsh"),
    customerName: "Jennifer Walsh",
    channel: "email",
    direction: "outbound",
    toAddress: "jen.walsh@example.com",
    fromAddress: KNOX_EMAIL,
    subject: "Your hardwood flooring estimate",
    body: "Hi Jennifer,\n\nThanks for having us out to measure. I've attached your hardwood estimate for the main level. Let me know if you'd like to walk through the options.\n\nBest,\nWill Knox",
    status: "delivered",
    providerMessageId: "seed-email-1",
    createdAt: dateTimeOffset(-4, 9, 15),
  },
  {
    id: "comm-2",
    leadId: "lead-1",
    customerKey: ck("Jennifer Walsh"),
    customerName: "Jennifer Walsh",
    channel: "email",
    direction: "inbound",
    toAddress: KNOX_EMAIL,
    fromAddress: "jen.walsh@example.com",
    subject: "Re: Your hardwood flooring estimate",
    body: "Hi Will,\n\nThis looks great. Could we go over the stain colors before we commit? Mornings work best for me.\n\nThanks,\nJennifer",
    status: "received",
    createdAt: dateTimeOffset(-3, 14, 2),
  },
  {
    id: "comm-3",
    leadId: "lead-1",
    customerKey: ck("Jennifer Walsh"),
    customerName: "Jennifer Walsh",
    channel: "sms",
    direction: "outbound",
    toAddress: "865-555-0201",
    fromAddress: KNOX_SMS,
    subject: "",
    body: "Hi Jennifer, this is Will at Knox Flooring. Confirming our stain color review tomorrow at 9am. Reply YES to confirm.",
    status: "delivered",
    providerMessageId: "seed-sms-1",
    createdAt: dateTimeOffset(-2, 16, 30),
  },
  {
    id: "comm-4",
    leadId: "lead-1",
    customerKey: ck("Jennifer Walsh"),
    customerName: "Jennifer Walsh",
    channel: "sms",
    direction: "inbound",
    toAddress: KNOX_SMS,
    fromAddress: "865-555-0201",
    subject: "",
    body: "YES — see you then!",
    status: "received",
    createdAt: dateTimeOffset(-2, 16, 41),
  },
  // Carlos Mendez (lead-2)
  {
    id: "comm-5",
    leadId: "lead-2",
    customerKey: ck("Carlos Mendez"),
    customerName: "Carlos Mendez",
    channel: "email",
    direction: "outbound",
    toAddress: "carlos.mendez@example.com",
    fromAddress: KNOX_EMAIL,
    subject: "Following up on your tile project",
    body: "Hi Carlos,\n\nGreat meeting you today. I'll get your kitchen tile estimate over by end of week. Let me know if anything changes in the meantime.\n\nThanks,\nDana Reed",
    status: "sent",
    providerMessageId: "seed-email-2",
    createdAt: dateTimeOffset(-5, 11, 0),
  },
  {
    id: "comm-6",
    leadId: "lead-2",
    customerKey: ck("Carlos Mendez"),
    customerName: "Carlos Mendez",
    channel: "sms",
    direction: "outbound",
    toAddress: "865-555-0202",
    fromAddress: KNOX_SMS,
    subject: "",
    body: "Hi Carlos, Dana from Knox Flooring here. Just sent your tile estimate by email — let me know if you have any questions!",
    status: "delivered",
    providerMessageId: "seed-sms-2",
    createdAt: dateTimeOffset(-1, 13, 20),
  },
  // Patricia Nguyen (lead-3)
  {
    id: "comm-7",
    leadId: "lead-3",
    customerKey: ck("Patricia Nguyen"),
    customerName: "Patricia Nguyen",
    channel: "email",
    direction: "inbound",
    toAddress: KNOX_EMAIL,
    fromAddress: "patricia.nguyen@example.com",
    subject: "Question about luxury vinyl plank",
    body: "Hello,\n\nI saw your work at a neighbor's home and would love a quote for LVP throughout my downstairs. What's your availability for an estimate?\n\nPatricia",
    status: "received",
    createdAt: dateTimeOffset(-6, 8, 45),
  },
  {
    id: "comm-8",
    leadId: "lead-3",
    customerKey: ck("Patricia Nguyen"),
    customerName: "Patricia Nguyen",
    channel: "email",
    direction: "outbound",
    toAddress: "patricia.nguyen@example.com",
    fromAddress: KNOX_EMAIL,
    subject: "Re: Question about luxury vinyl plank",
    body: "Hi Patricia,\n\nThank you for reaching out! We'd be glad to help. I have openings this Thursday and Friday afternoon for an in-home estimate. Which works better for you?\n\nBest,\nWill Knox",
    status: "delivered",
    providerMessageId: "seed-email-3",
    createdAt: dateTimeOffset(-6, 10, 12),
  },
];

export const SEED_MEASUREMENTS: MeasurementInsert[] = [
  // Demo lead (Marcus & Elena Whitfield) — measured and synced from Measure Square.
  {
    id: "meas-demo-1",
    leadId: "lead-1",
    externalId: "MS-204471",
    label: "Walsh Residence — Main Level",
    rooms: [
      { name: "Living Room", sqft: 342, lengthFt: 19, widthFt: 18, product: "Luxury Vinyl Plank" },
      { name: "Kitchen", sqft: 228, lengthFt: 19, widthFt: 12, product: "Luxury Vinyl Plank" },
      { name: "Hallway", sqft: 96, lengthFt: 24, widthFt: 4, product: "Luxury Vinyl Plank" },
      { name: "Dining Room", sqft: 196, lengthFt: 14, widthFt: 14, product: "Luxury Vinyl Plank" },
    ],
    products: [
      { name: "Shaw Floorté LVP — Coastal Oak", sku: "SW-LVP-CO", quantity: 940, unit: "sqft", sqft: 862 },
      { name: "Premium Underlayment", sku: "UL-PREM", quantity: 862, unit: "sqft" },
      { name: "Color-matched Quarter Round", sku: "TRM-QR", quantity: 180, unit: "lnft" },
    ],
    totalSqft: 862,
    total: 8533.8,
    measuredDate: daysFromNow(-6),
    source: "Measure Square",
    syncStatus: "synced",
    lastSyncedAt: dateTimeOffset(-2, 9, 5),
    isDemo: true,
    notes: "Pulled from Measure Square mobile measurement. Includes 8% waste factor.",
    createdAt: dateTimeOffset(-6, 15, 0),
    updatedAt: dateTimeOffset(-2, 9, 5),
  },
  // Demo lead — locally captured measurement not yet pushed to Measure Square.
  {
    id: "meas-demo-2",
    leadId: "lead-1",
    externalId: null,
    label: "Walsh Residence — Primary Suite",
    rooms: [
      { name: "Primary Bedroom", sqft: 285, lengthFt: 19, widthFt: 15, product: "Carpet" },
      { name: "Walk-in Closet", sqft: 88, lengthFt: 11, widthFt: 8, product: "Carpet" },
    ],
    products: [
      { name: "Mohawk SmartStrand Carpet — Greige", sku: "MH-SS-GR", quantity: 410, unit: "sqft", sqft: 373 },
      { name: "8lb Carpet Pad", sku: "PAD-8", quantity: 373, unit: "sqft" },
    ],
    totalSqft: 373,
    total: 2611.0,
    measuredDate: daysFromNow(-1),
    source: "Manual",
    syncStatus: "pending",
    lastSyncedAt: null,
    isDemo: true,
    notes: "Captured on-site; queued to push to Measure Square on next sync.",
    createdAt: dateTimeOffset(-1, 13, 30),
    updatedAt: dateTimeOffset(-1, 13, 30),
  },
  // Active job (Sarah Thompson, J-1001) — synced measurement tied to the job.
  {
    id: "meas-job-1",
    jobId: "1",
    externalId: "MS-204388",
    label: "Thompson — Whole Main Floor",
    rooms: [
      { name: "Great Room", sqft: 410, lengthFt: 20, widthFt: 20.5, product: "Luxury Vinyl Plank" },
      { name: "Kitchen & Nook", sqft: 264, lengthFt: 22, widthFt: 12, product: "Luxury Vinyl Plank" },
      { name: "Entry & Hall", sqft: 132, lengthFt: 33, widthFt: 4, product: "Luxury Vinyl Plank" },
    ],
    products: [
      { name: "COREtec Pro Plus — Hampton Oak", sku: "CT-PP-HO", quantity: 880, unit: "sqft", sqft: 806 },
      { name: "Premium Underlayment", sku: "UL-PREM", quantity: 806, unit: "sqft" },
    ],
    totalSqft: 806,
    total: 7657.0,
    measuredDate: daysFromNow(-10),
    source: "Measure Square",
    syncStatus: "synced",
    lastSyncedAt: dateTimeOffset(-3, 10, 20),
    isDemo: true,
    notes: "Approved measurement used for the installed scope.",
    createdAt: dateTimeOffset(-10, 14, 0),
    updatedAt: dateTimeOffset(-3, 10, 20),
  },
];
